# Generated by Django 3.1.6 on 2021-03-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(max_length=255)),
                ('add_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
